---
title: Cognitive dissonance
description: In this project I aim to assess the evidence for cognitive dissonance theory using a large-scaled replication study of a seminal cognitive dissonance study.
categories:
- cognitive dissonance
- replication
---

Cognitive dissonance refers to a state of aversive arousal that is experienced when people realize they possess mutually inconsistent cognitions. This state is the foundation of cognitive dissonance theory (CDT)---a theory developed by Leon Festinger in 1957. Several of my projects are aimed at assessing the evidence for this theory and at applying this theory to other issues (although now that I've left academia, these projects have been deprioritized).

## Why is this important?

The theory of cognitive dissonance can explain many different phenomena that we should understand so that we may intervene and improve the lives of others. For example, cognitive dissonance theory has been used to explain religious beliefs, unhealthy behaviors, and people's attitude towards animals.

Before the theory can be applied, however, it needs to be verified. We need to have sufficient evidence to believe in the theory. The social psychological evidence we have for the theory is, however, quite weak. The research stems from old research, mostly conducted in the 50s, 60s, and 70s. While this would not necessarily be a problem, it is a problem in the case of social psychology. The original studies were conducted with extremely low sample sizes and without pre-registration, or other tools that limit p-hacking. This means that many past findings may be false positives, which is supported by recent findings that show many findings in psychology do not replicate.

## What am I working on?

I am one of the lead investigators of a large-scaled replication project. In this project, we will try and replicate a seminal finding in the cognitive dissonance literature. Specifically, our aim is to replicate the classic finding that people who write a counterattitudinal essay (e.g., students arguing in favor of a tuition increase) become more in favor of the position they argued for. We have submitted this project as a registered report to Advanced in Methods and Practices in Psychological Science (AMPPS). There it has received an in-principle acceptance. Data collection is currently underway.

I also hope to start up a meta-analysis project to produce live reviews of studies from the cognitive dissonance literature.

## Links

-   The [landing page](https://docs.google.com/document/d/1eZMiXNlkUCe0x1DcnUQ29CN76UDgtyIFewcCNUkTJWE/ "Cognitive Dissonance RRR landing page") of our large-scaled replication project
-   The stage-1 accepted [manuscript](https://osf.io/52wpj "Cognitive Dissonance RRR manuscript")
