name = "Willem"
license = "MIT"
licenselink = "https://github.com/willemsleegers/willem/blob/master/LICENSE.md"
description = "My personal theme"
homepage = "https://xmin.yihui.name"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Willem Sleegers"
  homepage = "https://willemsleegers.com"
