project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "willemsleegers.com"
  site-url: https://www.willemsleegers.com/
  description: "The personal website of Willem Sleegers."
  reader-mode: true
  navbar:
    pinned: false
    collapse-below: md
    background: light
    left:
      - href: index.qmd
        text: Home
      - content/about.qmd
      - content/projects.qmd
      - content/blog.qmd
      - href: content/cv/cv.qmd
        text: CV
    right:
      - href: https://www.twitter.com/willemsleegers
        icon: twitter
      - href: https://www.github.com/willemsleegers
        icon: github
  page-footer: 
    left: "Copyright 2022 - Willem Sleegers" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/

format:
  html:
    toc: true
    theme: cosmo
    css: styles/styles.css
    csl: styles/apa.csl

freeze: auto

editor: visual
