baseurl: https://www.willemsleegers.com/
languageCode: en-us
title: Willem Sleegers
theme: me
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
      params:
        type: page
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
      params:
        type: pills
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 3
      params:
        type: blog
    - identifier: cv
      name: CV
      url: /CV/
      weight: 4
      params:
        type: page
permalinks:
  post: /:year/:month/:day/:slug/
params:
  description: "Willem Sleegers' personal website"
  favicon: /images/favicon.ico
  logo:
    text: "Willem Sleegers"
    domain: .com
  icons:
    - title: GitHub
      url: https://github.com/willemsleegers
      icon: github
    - title: Twitter
      url: https://twitter.com/willemsleegers
      icon: twitter
  home:
    avatar: avatar.png
    title: "Willem Sleegers"
    subtitle: "Assistant professor in social psychology"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
markup:
  goldmark:
    renderer:
      unsafe: true
