baseurl: https://www.davidreinstein.org/
languageCode: en-us
title: David Reinstein
theme: me
  #googleAnalytics = ""
  #math = true # Enable Katex globally
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
      params:
        type: page
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
      params:
        type: pills
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 3
      params:
        type: blog
    - identifier: cv
      name: CV
      url: /vitae/
      weight: 4
      params:
        type: page
permalinks:
  post: /:year/:month/:day/:slug/
params:
  description: "David Reinstein's personal professional website"
  favicon: /images/favicon.ico
  logo:
    text: "David Reinstein"
    domain: .org
  icons:
    - title: GitHub
      url: https://github.com/daaronr
      icon: github
    - title: Twitter
      url: https://twitter.com/GivingTools
      icon: twitter
  home:
    avatar: avatar.png
    title: "Willem Sleegers"
    subtitle: "Senior Economist at Rethink Priorities"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
markup:
  goldmark:
    renderer:
      unsafe: true
