baseurl = "https://www.willemsleegers.com"
languageCode = "en-us"
title = "Willem Sleegers"
theme = "me"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "CV"
    url = "/CV/"
    weight = 2
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 3
  [[menu.nav]]
    name = "Projects"
    url = "/project/"
    weight = 4

[params]
    heading = "Willem Sleegers"
    subheading = "Assistant professor in Social Psychology"
    twitter = "https://twitter.com/willemsleegers"
    github = "https://github.com/WillemSleegers"
    avatar = "img/avatar.png"
    footer = "&copy; Willem Sleegers 2020"
