{
  "hash": "1bb4c8404c338e4ececc9fcf20f09030",
  "result": {
    "markdown": "---\ntitle: \"Bayesian tutorial: Two groups\"\ndescription: \"The fourth of a series of tutorial posts on Bayesian analyses. In this post I focus on using `brms` to model the difference between two groups.\"\ndate: 2023-04-24\ncategories:\n  - statistics\n  - tutorial\n  - Bayesian statistics\n  - regression\ncode-fold: true\ncode-tools: true\ntoc: true\n---\n\n\nIn this blog post I will cover how to use `brms` to analyze the difference between two groups. Interestingly, this might seem like a very simple analysis, but there are actually multiple ways to go about this. I'll try to cover a few here.\n\nThe data we'll use is the same as in the previous posts. This data contains the sex of the participant in a column called `male`, in addition to their height, weight, and age. This means we can investigate, say, whether there's a difference in height between men and women.\n\nRun the following setup code if you want to follow along.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(tidybayes)\n\ndata <- read_csv(\"Howell1.csv\")\ndata <- filter(data, age >= 18)\n\ntheme_set(theme_minimal())\n\ncolor <- \"#1E466E\"\ncolors <- c(\"#93CFDB\", \"#1E466E\")\n```\n:::\n\n\n## Dummy coding\n\nProbably the most common method to analyze the difference between two groups is to regress the outcome on dummy coded data. That means the group column contains the information about both groups, usually using a 0 and 1 to indicate which group is which. The `male` column in the current data frame is dummy coded, with a 0 for females and a 1 for males. The R formula for regressing height on male is `height ~ male`. Let's see what priors we need to set for this by using the `get_prior()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(height ~ male, data = data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    prior     class coef group resp dpar nlpar lb ub\n                   (flat)         b                                 \n                   (flat)         b male                            \n student_t(3, 154.3, 8.5) Intercept                                 \n     student_t(3, 0, 8.5)     sigma                             0   \n       source\n      default\n (vectorized)\n      default\n      default\n```\n:::\n:::\n\n\nThe output shows we need to set a prior on sigma, the Intercept, and on the male coefficient. The intercept refers to the heights of female participants and the male coefficient refers to the difference between males and females, at least that's what you would expect in standard regression. We'll see that things are a bit more complicated. Sigma refers, as always, to the standard deviation of the residuals.\n\nWriting down this model shows that it's actually the same as the simple regression model:\n\n$$\\displaylines{heights_i ∼ Normal(\\mu_i, \\sigma) \\\\ \\mu_i = \\alpha + \\beta x_i}$$\n\nDespite this similarity, there's an issue here that we need to get into. Let's demonstrate this issue by setting some priors and running the model while only sampling from the priors. This means the estimates we get for the intercept and male coefficient should match our priors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_dummy_priors_default <- brm(\n  height ~ male,\n  data = data,\n  family = gaussian,\n  prior = c(\n    prior(normal(165, 5), class = \"Intercept\"),\n    prior(normal(10, 5), coef = \"male\"),\n    prior(cauchy(5, 5), class = \"sigma\")\n  ),\n  sample_prior = \"only\",\n  cores = 4,\n  seed = 4,\n  file = \"./models/model-dummy-priors-default.rds\"\n)\n\nmodel_dummy_priors_default\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: height ~ male \n   Data: data (Number of observations: 352) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   160.32      5.63   148.76   171.25 1.00     3054     2599\nmale          9.92      5.12    -0.25    19.93 1.00     2832     2696\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    22.69    187.60     0.62    90.80 1.00     3302     1765\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\nLooking at the estimates we see that the estimate for male is indeed around 10 but the intercept estimate is not close to what we set it too. In this case, the intercept has an estimate of around 160, even though we set it to 165. How can this be? The reason is that `brms` internally centers the intercept so that it corresponds to the expected response when all predictors are held at their means. This is what the prior is set to, not to the mean of the heights of female participants. `brms` also re-generates the true intercept, which is the one we see in the output, so the intercept in the output does correctly indicate the mean height of female participants. Confusing.\n\nTo prevent this from happening, we need to suppress the default intercept and explicitly add one as a coefficient. This means we need to update our prior for the intercept to refer to a `coef` (instead of `class`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_dummy_priors <- brm(\n  height ~ 0 + Intercept + male,\n  data = data,\n  family = gaussian,\n  prior = c(\n    prior(normal(165, 5), coef = \"Intercept\"),\n    prior(normal(10, 5), coef = \"male\"),\n    prior(cauchy(5, 5), class = \"sigma\")\n  ),\n  sample_prior = \"only\",\n  cores = 4,\n  seed = 4,\n  file = \"./models/model-dummy-priors.rds\"\n)\n\nmodel_dummy_priors\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: height ~ 0 + Intercept + male \n   Data: data (Number of observations: 352) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   165.04      5.12   154.88   175.06 1.00     2924     2468\nmale         10.11      5.01     0.10    19.82 1.00     3452     2556\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    17.96     96.44     0.55    83.00 1.00     3111     2025\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\nThe estimates (i.e., our priors) show that the average height for women is 165.04 and that for men is 165.04 + 10.11 = 175.15.\n\nBut now there's a new problem. Let's take a look at how uncertain we should be at these estimates by predicting the means for both men and women and then calculating the width of the 95% quartile interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(male = c(0, 1)) %>%\n  add_epred_draws(model_dummy_priors) %>%\n  median_qi() %>%\n  mutate(width = .upper - .lower)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 9\n   male  .row .epred .lower .upper .width .point .interval width\n  <dbl> <int>  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>     <dbl>\n1     0     1   165.   155.   175.   0.95 median qi         20.2\n2     1     2   175.   161.   189.   0.95 median qi         28.6\n```\n:::\n:::\n\n\nWe see that the width for males is slightly wider than that for females. If you run the model multiple times at different seeds, you'll see that this is something that happens consistently. The reason there is more uncertainty for the mean of male participants is that we've added a separate prior that only applies to males---the prior on the male coefficient. The mean of female participants is wholly determined by the data and the prior on the intercept, but for males it's the data and the prior for the intercept + the prior for the male coefficient. This is not desirable.\n\nOn top of that it less intuitive to think about the priors as a mean for females and then a prior for how much males deviate from this mean. It seems nicer to just specify what we think the heights are for females and what the heights are for males, without thinking about the deviation.\n\nBoth of these issues can be solved by using index coding instead of dummy coding.\n\n## Index coding\n\nIndex coding requires that we create a new column that is a factor or that contains string values to indicate the sex of the participant. Below I create a new column called `sex` that contains the values `male` and `female` as string values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- mutate(data, sex = if_else(male == 1, \"male\", \"female\"))\n```\n:::\n\n\nLet's see what the priors are that we need to set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(height ~ 0 + sex, data = data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                prior class      coef group resp dpar nlpar lb ub       source\n               (flat)     b                                            default\n               (flat)     b sexfemale                             (vectorized)\n               (flat)     b   sexmale                             (vectorized)\n student_t(3, 0, 8.5) sigma                                  0         default\n```\n:::\n:::\n\n\nWe need a prior for sigma, as always, and two priors for the two sexes.\n\nWe should also alter how we describe this model. We can now drop the $\\beta$ parameter from the model and we should more explicitly indicate that we will model several $\\alpha$ parameters, one for each sex.\n\n$$\\displaylines{heights_i ∼ Normal(\\mu_i, \\sigma) \\\\ \\mu_i = \\alpha_{sex[i]}}$$\n\nNext, I simply translated the previous priors to this new notation. The prior for the heights of female participants stays the same (a normal distribution with a mean of 165 and a standard deviation of 5). The prior for the heights of male participants is also still a normal distribution, but now with a mean of 175 (165 + 10) and the same standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_index_prior <- brm(\n  height ~ 0 + sex,\n  data = data,\n  family = gaussian,\n  prior = c(\n    prior(normal(165, 5), coef = \"sexfemale\"),\n    prior(normal(175, 5), coef = \"sexmale\"),\n    prior(cauchy(5, 5), class = \"sigma\")\n  ),\n  sample_prior = \"only\",\n  cores = 4,\n  seed = 4,\n  file = \"./models/model-index-prior.rds\"\n)\n\nmodel_index_prior\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: height ~ 0 + sex \n   Data: data (Number of observations: 352) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsexfemale   165.01      4.99   155.25   174.56 1.00     3013     2701\nsexmale     175.11      5.05   165.41   185.14 1.00     2823     2546\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    57.54   1744.14     0.56    96.43 1.00     3387     2055\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\nLet's confirm that the uncertainty in the priors for the male and female average heights are the same.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(sex = c(\"male\", \"female\")) %>%\n  add_epred_draws(model_index_prior) %>%\n  median_qi() %>%\n  mutate(width = .upper - .lower)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 9\n  sex     .row .epred .lower .upper .width .point .interval width\n  <chr>  <int>  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>     <dbl>\n1 female     2   165.   155.   175.   0.95 median qi         19.3\n2 male       1   175.   165.   185.   0.95 median qi         19.7\n```\n:::\n:::\n\n\nThey are. This means we can now run the model and also sample from the posterior.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_index <- brm(\n  height ~ 0 + sex,\n  data = data,\n  family = gaussian,\n  prior = c(\n    prior(normal(165, 5), coef = \"sexfemale\"),\n    prior(normal(175, 5), coef = \"sexmale\"),\n    prior(cauchy(5, 5), class = \"sigma\")\n  ),\n  sample_prior = TRUE,\n  cores = 4,\n  seed = 4,\n  file = \"./models/model-index.rds\"\n)\n\nmodel_index\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: height ~ 0 + sex \n   Data: data (Number of observations: 352) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsexfemale   149.62      0.41   148.81   150.40 1.00     4239     2995\nsexmale     160.47      0.43   159.63   161.31 1.00     4245     2663\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     5.56      0.21     5.16     5.99 1.00     3837     2992\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\nThe estimates show, more clearly now, that the average height for women is 149.62 and that for men is 160.47.\n\n## Calculating a difference score\n\nIn the previous section I've argued that we should use index coding so that we can more easily think about, and see the results, of the priors about the two groups. I realize, though, that we are often still interested in the difference between the groups. This is easy to obtain, though. We can simply take the posterior samples from each group and subtract them from each other.\n\nIn the code below I extract the draws of each parameter (`b_sexfemale` and `b_sexmale`) and calculate the difference score. I then extract the draws of the difference score and calculate the median and quartile interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_index %>%\n  spread_draws(b_sexfemale, b_sexmale) %>%\n  mutate(difference = b_sexmale - b_sexfemale) %>%\n  pull(difference) %>%\n  median_qi()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         y     ymin     ymax .width .point .interval\n1 10.84426 9.729488 12.02288   0.95 median        qi\n```\n:::\n:::\n\n\nAlternatively, we can also plot it as a distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws <- model_index %>%\n  spread_draws(b_sexfemale, b_sexmale) %>%\n  mutate(difference = b_sexmale - b_sexfemale)\n\nggplot(draws, aes(x = difference)) +\n  geom_histogram(fill = color) +\n  labs(x = \"Difference\", y = \"\")\n```\n\n::: {.cell-output-display}\n![](bayesian-tutorial-2-groups_files/figure-html/difference-score-plot-1.png){width=672}\n:::\n:::\n\n\n## Summary\n\nJust like running a correlation, testing a group difference consists of running a simple regression. However, having groups as a predictor means the regression is not so simple after all. You have to think more carefully about what the priors mean (particularly the intercept) and you have to deal with greater uncertainty for some estimates, depending on how you code the group predictor. I've shown that explicitly including the intercept and using index coding makes thinking about this scenario a bit easier.",
    "supporting": [
      "bayesian-tutorial-2-groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}