---
title: "Bayesian tutorial: Likert data"
description: "The fifth of a series of tutorial posts on Bayesian analyses. In this post I focus on using brms to model Likert data."
date: 2023-04-24
categories:
  - statistics
  - tutorial
  - Bayesian statistics
  - regression
  - Likert
code-fold: true
code-tools: true
toc: true
draft: true
---

Run the following setup code if you want to follow along.

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(likert)
library(brms)
library(tidybayes)
library(modelr)

theme_set(theme_minimal())

options(
  mc.cores = 4,
  brms.threads = 4,
  brms.backend = "cmdstanr",
  brms.file_refit = "on_change",
  brms.silent = 2
)
```

```{r}
#| label: data-inspection
?likert::likert.bar.plot()

data(pisaitems)
items29 <- pisaitems[, substr(names(pisaitems), 1, 5) == "ST25Q"]
names(items29) <- c(
  "Magazines", "Comic books", "Fiction",
  "Non-fiction books", "Newspapers"
)

get_prior(Magazines ~ 1,
  data = items29,
  family = cumulative("probit")
)

items29 <- items29 |>
  as_tibble() |>
  mutate(Magazines = factor(Magazines, ordered = TRUE)) |>
  filter(!is.na(Magazines))

count(items29, Magazines)


model <- brm(
  Magazines ~ 1,
  data = items29,
  family = cumulative("probit"),
  sample_prior = "yes",
  file = "models/likert.rds",
)

data_grid(.model = model) |>
  add_epred_draws(model) |>
  median_qi()

```

*This post was last updated on `r format(Sys.Date(), "%Y-%m-%d")`.*