---
title: Useful power analysis papers
description: "A curious thing happened in the field of social psychology: Social psychologists finally realized that statistical power is important. Unfortunately, they then skipped the step of figuring out how to do them correctly. Here I list some papers on power analyses that I hope help in improving the way we do them."
date: 2020-08-01
categories:
  - statistics
  - power analysis
---

## Papers

-   Maxwell, S. E. (2004). The persistence of underpowered studies in psychological research: Causes, consequences, and remedies. *Psychological Methods*, *9*(2), 147--163. <https://doi.org/10.1037/1082-989X.9.2.147>

This paper is quite amazing. It covers almost everything you need to be aware of when it comes to the state of our field, including how badly powered most studies are, how this affects the interpretability of inconsistencies in the literature, the need for multisite projects, and so on!

Most importantly, it is about the problem of multiple statistical tests. Many power analyses that I see in the literature only power for one analysis, even though a paper usually contains many more. If you want a shot at all of those analyses being able to show something, you need to power for it all.

-   Blake, K. R., & Gangestad, S. (2020). On attenuated interactions, measurement error, and statistical power: Guidelines for social and personality psychologists. *Personality and Social Psychology Bulletin.* <https://doi.org/10.1177/0146167220913363>

This is a great paper on a common pitfall in power analyses for attenuated interaction tests. Attenuated interactions are interactions where you expect a predictor to have an effect in one condition, but not another. They show that in a 2 x 2 design, you should use a fourfold of the sample size that is needed to show the interaction effect. Of course, this only applies when you predict a perfect attenuated interaction (a complete absence of the effect in the other condition, rather than a diminished one) and that you do not have any measurement error.
