{
  "hash": "fe0d1ad4a7d560b42f53efde1fe90c99",
  "result": {
    "markdown": "---\ntitle: \"Bayesian tutorial: Intercept-only model\"\ndescription: \"The first of a series of tutorial posts on Bayesian analyses. In this post I focus on using `brms` to run an intercept-only regression model.\"\ndate: 2023-02-01\ncategories:\n  - statistics\n  - tutorial\n  - Bayesian statistics\n  - regression\ncode-fold: true\ncode-tools: true\ntoc: true\nformat: \n   html:\n     df-print: kable\n---\n\n\nThis post is the first of a series of tutorial posts on Bayesian statistics. I'm not an expert on this topic, so this tutorial is partly, if not mostly, a way for me to figure it out myself.\n\nThe goal will be to go through each step of the data analysis process and make things as intuitive and clear as possible. I'll use the `brms` package to run the models and I will rely heavily on the book [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/ \"Statistical Rethinking website\") by Richard McElreath.\n\nThe basic idea behind Bayesian statistics is that we start off with prior beliefs about the parameters in the model and then update those beliefs using the data. That means that for all subsequent models you need to figure out what your beliefs are before running any analyses. This is very different from frequentist statistics and probably the most off-putting part of running Bayesian analyses. However, my goal is to make this relatively easy by focusing on visualizing priors and how they change as a function of the Bayesian process. I'll also try to come up with some methods to simplify the construction of priors, with the goal to have them be reasonable and non-controversial.\n\nIn some cases I might not even use a prior I personally believe in. Instead I'll use a prior that represents a particular position or skepticism so that the results of the analysis can be used to change the mind of the skeptic, rather than me changing whatever I happen to believe.\n\nWith this in mind, let's begin.\n\n## Setup\n\nIn the code chunk below I show some setup code to get started, starting with the packages. After loading the packages I set the default `ggplot2` theme and create a color palette consisting of two colors. Finally, I set a `brms` specific option to automatically re-run models if a model has changed. If not, the results will be read from a file to speed things up.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(marginaleffects)\n\ntheme_set(theme_minimal())\ncolors <- c(\"#93CFDB\", \"#1E466E\")\n\noptions(brms.file_refit = \"on_change\")\n```\n:::\n\n\n## Data\n\nThe [data](Howell1.csv) I'll play with is the same data Richard McElreath uses in Chapter 4 of his amazing book Statistal Rethinking. The data consists of partial census data of the !Kung San, compiled from interviews conducted by Nancy Howell in the late 1960s. Just like in the book, I will focus only on people 18 years or older.\n\n\n::: {.cell tbl-cap='Partial census data for the Dobe area !Kung San compiled by Nancy Howell in the late 1960s.'}\n\n```{.r .cell-code}\ndata <- read_csv(\"Howell1.csv\")\ndata <- filter(data, age >= 18)\n\nhead(data)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  height|   weight| age| male|\n|-------:|--------:|---:|----:|\n| 151.765| 47.82561|  63|    1|\n| 139.700| 36.48581|  63|    0|\n| 136.525| 31.86484|  65|    0|\n| 156.845| 53.04191|  41|    1|\n| 145.415| 41.27687|  51|    0|\n| 163.830| 62.99259|  35|    1|\n\n</div>\n:::\n:::\n\n\n## An intercept-only model\n\nLet's focus the first question on the heights in the data. What are the heights of the Dobe area !Kung San?\n\nThe way to address this question is by constructing a model in which heights are regressed on only the intercept, i.e., an intercept-only model. You may be familiar with the R formula for this type of model: `height ~ 1`.\n\nWith this formula and the data we can use `brms` to figure out which priors we need to set by running the `get_prior()` function. This is probably the easiest way to figure which priors you need when you're just starting out using `brms`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(height ~ 1, data = data)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|prior                    |class     |coef |group |resp |dpar |nlpar |lb |ub |source  |\n|:------------------------|:---------|:----|:-----|:----|:----|:-----|:--|:--|:-------|\n|student_t(3, 154.3, 8.5) |Intercept |     |      |     |     |      |   |   |default |\n|student_t(3, 0, 8.5)     |sigma     |     |      |     |     |      |0  |   |default |\n\n</div>\n:::\n:::\n\n\nThe output shows us that we need to set two priors, one for the Intercept and one for sigma. `brms` already determined a default prior for each parameter (they are required for a Bayesian analysis), so we could immediately run an analysis if we want to but it is recommended to construct your own priors.\n\nAlso, using the `get_prior()` function is not the best way to think about which priors we need. Using the function will give us the answer, but it doesn't really improve our understanding of why these two priors are needed. In this case I also omitted an important specification of the heights, which is that they are normally distributed (the default assumption in `get_prior()`). So let's instead write down the model in a different way, which explicitly specifies how we think the heights are distributed and which parameters we need to set priors on. If we think the heights are normally distributed, we define our model like this:\n\n$$heights_i ∼ Normal(\\mu, \\sigma)$$\n\nWe explicitly note that the individual heights come from a normal distribution, which is determined by the parameters $\\mu$ and $\\sigma$. This then also immediately tells us that we need to set two priors, one on $\\mu$ and one on $\\sigma$.\n\nIn our intercept-only model, the $\\mu$ parameter refers to our intercept and the $\\sigma$ parameter refers to, well, sigma. Sigma is not often discussed in the literature I'm familiar with, but we'll figure it out below. In fact, let's discuss each of these parameters in turn and figure out what kind of prior makes sense.\n\n## The intercept ($\\mu$) prior\n\nThe prior for the intercept indicates what I believe the *average* height of the !Kung San to be.\n\n`brms` has set the default intercept prior as a Student *t*-distribution with 3 degrees of freedom, a mean of 154.3 and a standard deviation of 8.5. That means `brms` starts off with a 'belief' that the *average* of the heights is 154.3, but with quite some uncertainty reflected in the standard deviation of 8.5 and the fact that the distribution is a Student *t*-distribution. A Student *t*-distribution has thicker tails compared to a normal distribution, meaning that numbers in the tails of the distribution are more likely compared to a normal distribution, at least when the degrees of freedom are low. At higher degrees of freedom, the *t*-distribution becomes more and more like the normal distribution. So, the thicker tails of the *t*-distributions means smaller and taller average heights are relatively more plausible.\n\nBut this is the default prior. `brms` determines this prior by peeking at the data to create a weak prior that is easily updated by the data. We can generally do better than the default priors, which is why it is recommended to create our own.\n\nSo what do I believe the average height to be? As a Dutch person, I might be under the impression that the average height is around 175 centimeters. This is probably too tall to use as an average for the !Kung San because we're known for being quite tall. So I think the average should be lower than 175, perhaps 170. I am not very sure, though. After all, I am far from an expert on people's heights; I am only using my layman knowledge here. An average of 165 seems possible to me too. So let's describe my belief in the form of a distribution in which multiple averages are possible, to varying extents. We should use a Student *t*-distribution with small degrees of freedom if we want to allow for the possibility of being very wrong (remember, it has thicker tails, so it assigns more probability to a wider range of average heights). We're not super uncertain about people's heights, though, so let's use a normal distribution.\n\nAs we saw in defining our height model, a normal distribution requires that we set two parameters: the $\\mu$ and the $\\sigma$. The $\\mu$ we already covered (i.e., 170), so that leaves $\\sigma$. Let's set this to 10 and see what happens by visualizing this prior. Below I plot both the default `brms` prior and our own with $\\mu$ = 170 and $\\sigma$ = 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheight_prior_intercept <- tibble(\n  height_mean = seq(from = 100, to = 250, by = 0.1),\n  mine = dnorm(height_mean, mean = 170, sd = 10),\n  default = dstudent_t(height_mean, df = 30, mu = 154.3, sigma = 8.5),\n)\n\nheight_prior_intercept <- pivot_longer(\n  height_prior_intercept,\n  cols = -height_mean,\n  names_to = \"prior\"\n)\n\nggplot(\n  height_prior_intercept,\n  aes(x = height_mean, y = value, linetype = fct_rev(prior))\n) +\n  geom_line() +\n  labs(x = \"Average height\", y = \"\", linetype = \"Prior\") +\n  scale_x_continuous(breaks = seq(100, 250, 20))\n```\n\n::: {.cell-output-display}\n![Two priors for $\\mu$](bayesian-tutorial-intercept-only_files/figure-html/height-mu-prior-1.png){width=672}\n:::\n:::\n\n\nMy prior indicates that I believe the average height to be higher than the default prior. In terms of the standard deviation, we both seem to be about equally uncertain about this average. Looking at this graph I think this prior of mine is not very plausible. Apparently I assign quite a chunk of plausibility to an average of 180 cm, or even 190 cm, which is very unlikely. An average of 160 cm is more plausible to me than an average of 180, so I should probably lower the mu, or use more of a skewed distribution. This is one of the benefits of visualizing the prior, it can make you think again about your prior so that you may improve on it. Based on the graph, I will change the mean of my prior to 160. I can probably also lower the standard deviation, but I'll leave it at 10 to show how easily the data will update this prior.\n\n## The sigma ($\\sigma$) prior\n\nWhat about the sigma prior? What even is sigma? Sigma is the estimated standard deviation of the errors or, in other words, the standard deviation of the residuals of the model. In the simple case of an intercept-only model, this is identical to the standard deviation of the outcome (heights, in this case).\n\nI think setting the standard deviation of the distribution of heights (not the mean of the heights) is quite difficult. There are parts that are easy, such as the fact that the standard deviation has to be 0 or larger (it can't be negative), but exactly how large it should be, I don't know.\n\nI do know it is unlikely to be close to 0, and unlikely to be very large. That's because I know people's heights do vary, so I know the sigma can't be 0. I also know it's not super large because we don't see people who are taller than 2 meters very often. This means the peak of our prior should be somewhere above 0, with a tail to allow higher values but not too high. We can use a normal distribution for this with a mean above 0 and a particular standard deviation, and ignore everything that's smaller than 0 (`brms` automatically ignores negative values for $\\sigma$).\n\nAs I mentioned before, there is a downside of using a normal distribution, though. Normal distributions have long tails, but there is actually very little density in those tails. If we are quite uncertain about our belief about sigma, we should use a *t*-distribution, or perhaps even a cauchy distribution (actually, the cauchy distribution is a special case of the *t*-distribution; they are equivalent if the degree of freedom is 1). The lower the degrees of freedom, the more probability we assign to higher and lower values.\n\nA *t*-distribution requires three parameters: $\\mu$, $\\sigma$, and the degrees of freedom. I set $\\mu$ to 5, $\\sigma$ to 5, and the degrees of freedom to 1. Below I plot this prior and `brms`'s default prior to get a better grasp of these priors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheight_prior_sigma <- tibble(\n  height_sigma = seq(from = 0, to = 50, by = .1),\n  default = dstudent_t(height_sigma, df = 3, mu = 0, sigma = 8.5),\n  mine = dstudent_t(height_sigma, df = 1, mu = 5, sigma = 5)\n)\n\nheight_prior_sigma <- pivot_longer(\n  height_prior_sigma,\n  cols = -height_sigma,\n  names_to = \"prior\"\n)\n\nggplot(\n  height_prior_sigma,\n  aes(x = height_sigma, y = value, linetype = fct_rev(prior))\n) +\n  geom_line() +\n  labs(x = \"Standard deviation of heights\", y = \"\", linetype = \"Prior\")\n```\n\n::: {.cell-output-display}\n![Two priors for $\\sigma$](bayesian-tutorial-intercept-only_files/figure-html/height-sigma-prior-1.png){width=672}\n:::\n:::\n\n\nAs you can see, both distributions have longish tails, allowing for the possibility of high standard deviations. There are some notable differences between the two priors, though. Our prior puts more weight on a standard deviation larger than 0, while the default prior reflects a belief in which a standard deviation of 0 is most likely. However, both priors are quite weak.\n\n## Prior predictive check\n\nSo far we have inspected each prior in isolation, but we can also use our priors to simulate heights and see if the distribution of heights makes sense. This is called a prior predictive check.\n\nI'll use `brms` to do this by running the `brm()` function. The `brm()` function is the main work horse of the `brms` package. It allows us to run Bayesian analyses by using a common notation style familiar to those who use R. This is also one of the reasons why the `brms` package is so great; it's very easy to get started with running Bayesian analyses.\n\nThe `brm()` function requires a model specification and the data. Optionally, but usefully, we should also specify the response distribution (a normal distribution by default) and the priors.\n\nHowever, we're not ready to actually run the model just yet. Instead, we will kinda trick `brms` into running an analysis, but tell it to only sample from the prior using the `sample_prior` argument. This will enable us to get 'predicted' responses based entirely on our priors and not the data.\n\nAdditionally, we also set the number of cores to speed up the analysis, a seed to make the results reproducible, and a file to store the results into so that if we run the analysis again, we can simply read the results from the file rather than running the analysis again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_height_prior <- brm(\n  height ~ 1,\n  data = data,\n  family = gaussian,\n  prior = c(\n    prior(normal(160, 10), class = \"Intercept\"),\n    prior(cauchy(5, 5), class = \"sigma\")\n  ),\n  sample_prior = \"only\",\n  cores = 4,\n  seed = 4,\n  file = \"models/model_height_prior.rds\"\n)\n```\n:::\n\n\nThe next part is a little odd because we will visualize the distribution of predicted heights by visualizing draws from this distribution (as opposed to some analytic formula that describes the distribution). By default, `brms` will draw 4000 draws. We could use the `predict()` function to do this (e.g., `predict(model_height_prior)`, but I prefer to use the `marginaleffects` package because it's a really nice package that will simplify things further down the road.\n\nThe `marginaleffects` function to use is `predictions()` and `posterior_draws()`. The `predictions()` function takes a model object and optionally a new data frame to create predictions for each row in the data frame. This is a little tricky because by default it will use the data from the model itself, which would create a new data frame that has rows equal to the number of rows in the original data frame. This is not needed in our case because we're only interested in a single number (the average height). On top of that, after running the `predictions()` function we want to run the `posterior_draws()` function to obtain the draws of the posterior so that we can visualize it. If we get the predictions of every single row in the original data frame, we would end up with a new data frame with rows equal to the number of rows in the original data frame times the number of draws (4000 by default). We don't want to have such a large data frame. So, because we're dealing with an intercept-only model that has no predictors, we will create an almost empty data frame. I want to re-use these results later to compare the prior to the posterior results, so I'll simply add a column in this almost empty data frame to say that these results are from a prior distribution. After getting the predictions, we use the `posterior_draws()` function to obtain the draws.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheights_prior <- model_height_prior %>%\n  predictions(newdata = tibble(distribution = \"prior\"), type = \"prediction\") %>%\n  posterior_draws()\n\nggplot(heights_prior, aes(x = draw)) +\n  geom_histogram(binwidth = 1, alpha = .85) +\n  xlim(100, 250) +\n  labs(x = \"Height\", y = \"\")\n```\n\n::: {.cell-output-display}\n![Prior predictive check](bayesian-tutorial-intercept-only_files/figure-html/prior-predictive-1.png){width=672}\n:::\n:::\n\n\nOur priors result in a normal distribution of heights with the bulk of the observations ranging from about 125 cm to 200 cm. That seems fairly reasonable to me, as someone who doesn't know too much about the heights of the !Kung San.\n\n## Running the model\n\nNow that the priors are in order we can run the model with the code below. Notice that this time I omit the `sample_prior` argument so we only obtain the posterior results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_height <- brm(\n  data = data,\n  family = gaussian,\n  height ~ 1,\n  prior = c(\n    prior(normal(160, 10), class = \"Intercept\"),\n    prior(cauchy(5, 5), class = \"sigma\")\n  ),\n  cores = 4,\n  seed = 4,\n  file = \"models/model_height.rds\"\n)\n```\n:::\n\n\nAfter running the model, we first check whether the chains look like caterpillars because that indicates we have samples from the entire distribution space of the posteriors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model_height)\n```\n\n::: {.cell-output-display}\n![](bayesian-tutorial-intercept-only_files/figure-html/chains-1.png){width=672}\n:::\n:::\n\n\nThe chains look good.\n\nWe can call up the estimates and the 95% confidence intervals by printing the model object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_height)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: height ~ 1 \n   Data: data (Number of observations: 352) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   154.62      0.42   153.78   155.47 1.00     2613     2354\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     7.76      0.30     7.21     8.37 1.00     3290     2585\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\nHere we see the Intercept and sigma estimates. Apparently our posterior estimate for the Intercept is 154.62 and the estimate for $\\sigma$ is 7.76. We also see the 95% CIs, but let's visualize these results instead.\n\nInspecting the chains also showed us the posterior distributions of the two parameters, but let's create our own graphs that compare both the prior and posterior distributions. We can use the `as_draws_df()` function from `brms` to get draws from each parameter in the model. In the code below I do that twice, once to get the draws from our previous model that sampled from the prior only and once from our new model. The result for each is a data frame and I'll add a column to indicate whether the draw is from the prior or posterior.\n\n\n::: {.cell fig.cap-='Prior vs. posterior for $\\mu$'}\n\n```{.r .cell-code}\ndraws_prior <- model_height_prior %>%\n  as_draws_df() %>%\n  mutate(distribution = \"prior\")\n\ndraws_posterior <- model_height %>%\n  as_draws_df() %>%\n  mutate(distribution = \"posterior\")\n\ndraws <- bind_rows(draws_prior, draws_posterior)\n\nggplot(draws, aes(x = b_Intercept, fill = fct_rev(distribution))) +\n  geom_histogram(binwidth = 1, position = \"identity\", alpha = .85) +\n  xlim(145, 195) +\n  labs(\n    x = \"Intercept (i.e., average height)\",\n    y = \"\",\n    fill = \"Distribution\"\n  ) +\n  scale_fill_manual(values = colors)\n```\n\n::: {.cell-output-display}\n![](bayesian-tutorial-intercept-only_files/figure-html/prior-posterior-mu-1.png){width=672}\n:::\n:::\n\n\nHere we see that the posterior distribution of average heights is much more narrow and centered around 155 cm. So not only should we switch from thinking the average is lower than 160, we can also be much more confident about the mean.\n\nHow about sigma?\n\n\n::: {.cell fig.cap-='Prior vs. posterior for $\\sigma$'}\n\n```{.r .cell-code}\nggplot(draws, aes(x = sigma, fill = fct_rev(distribution))) +\n  geom_histogram(binwidth = 0.25, position = \"identity\", alpha = .85) +\n  xlim(0, 25) +\n  labs(\n    x = \"Sigma (i.e., height standard deviation)\",\n    y = \"\",\n    fill = \"Distribution\"\n  ) +\n  scale_fill_manual(values = colors)\n```\n\n::: {.cell-output-display}\n![](bayesian-tutorial-intercept-only_files/figure-html/prior-posterior-sigma-1.png){width=672}\n:::\n:::\n\n\nSimilarly, we see that the posterior for sigma is also much more narrow and around 8.\n\nA final step is to conduct a posterior predictive check. Since we also conducted a prior predictive check we can plot both and compare how our overall beliefs about the distribution of heights should change as a function of the data. Below I create a new data frame with draws from the posterior, just like when I created the prior predictive check, and merge it with the prior data frame from before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheights_posterior <- model_height %>%\n  predictions(newdata = tibble(distribution = \"posterior\"), type = \"prediction\") %>%\n  posterior_draws()\n\nheights <- bind_rows(heights_prior, heights_posterior) %>%\n  mutate(distribution = fct_relevel(distribution, \"prior\"))\n\nggplot(heights, aes(x = draw, fill = distribution)) +\n  geom_histogram(binwidth = 1, alpha = .85, position = \"identity\") +\n  xlim(100, 250) +\n  labs(x = \"Height\", y = \"\", fill = \"Distribution\") +\n  scale_fill_manual(values = colors)\n```\n\n::: {.cell-output-display}\n![Prior and posterior predictive check](bayesian-tutorial-intercept-only_files/figure-html/prior-posterior-predictive-check-1.png){width=672}\n:::\n:::\n\n\nAnd that's it!\n\n## Summary\n\nIn this post I showed how to run an intercept-only model in `brms`. It consisted of the following steps:\n\n1.  Define the model\n2.  Use the model to figure out which priors to set\n3.  Visualize the priors and create a prior predictive check to potentially tweak the priors\n4.  Run the model using `brms`\n5.  Inspect the output of `brms`, including the chains\n6.  Obtain draws of the estimates and visualize their distribution\n7.  Compare the prior predictive check to the posterior results to see how much to update based on the data\n\nIn the next post I'll show how to add a predictor to the model.\n\n*This post was last updated on 2023-05-10.*",
    "supporting": [
      "bayesian-tutorial-intercept-only_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}