---
title: Useful power analysis papers
author: Willem Sleegers
date: '2020-03-27'
slug: useful-power-analysis-papers
tags:
  - statistics
  - power analysis
---

In this post I list papers that are useful for understanding power analyses. A crazy thing happened in the field of social psychology. Somehow people became of the opinion that psychologists *must* do power analyses, but without knowing how to do them. I have rarely seen a correct power analysis being conducted. Hopefully the papers below will be helpful in improving the way we do them.

## Papers

- Maxwell, S. E. (2004). The persistence of underpowered studies in psychological research: Causes, consequences, and remedies. *Psychological Methods*, *9*(2), 147–163. https://doi.org/10.1037/1082-989X.9.2.147

This paper is quite amazing. It covers almost everything you need to be aware of when it comes to the state of our field, including how badly powered most studies are, how this affects the interpretibility of inconsistencies in the literature, the need for multi-site projects, and so on!

Most importantly, it is about the problem of multiple statistical tests. Many power analyses that I see in the literature only power for one analysis, even though a paper usually contains many more. If you want a shot at all of those analyses being able to show something, you need to power for it all.

- Blake, K. R., & Gangestad, S. (2020). On attenuated interactions, measurement error, and statistical power: Guidelines for social and personality psychologists. *Personality and Social Psychology Bulletin.* https://doi.org/10.1177/0146167220913363

This is a great paper on a common pitfall in power analyses for attentuated interaction tests. Attenuated interactions are interactions where you expect a predictor to have an  effect in one condition, but not another. They show that in a 2 x 2 design, you should use a fourfold of the sample size that is needed to show the interaction effect. Of course, this only applies when you predict a perfect attenuated interaction (a complete absence of the effect in the other condition, rather than a diminished one) and that you do not have any measurement error.

This post was last updated on `r format(Sys.Date(), "%Y-%m-%d")`.
